apiVersion: v1
kind: Service
metadata:
  name: api-node
  labels:
    app.kubernetes.io/name: api-node
    app.kubernetes.io/part-of: laboratorio
spec:
  type: ClusterIP # sem Load Balancer no laboratório: acesso por port-forward
  selector:
    app.kubernetes.io/name: api-node
  ports:
    - name: http
      port: 80
      targetPort: http
